# Generated by Django 4.2.30 on 2026-06-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedback_delete_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='originator_conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
